### ISSUE TITLE
IPAM to DNS replication

### ISSUE THREAD

**Issue by pablo-ruth** [EfficientIP-Labs/terraform-provider-solidserver#11]
Hello,

We have a problem when we use the provider to create an ip with the resource "solidserver_ip_address". We have a block like this one:
```
resource "solidserver_ip_address" "ip" {
  space  = "MAIN"
  subnet = "SIEGE"
  pool   = "TEAM1"
  name   = "myhost.domaine.local"
}
```
The creation is ok:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # solidserver_ip_address.ip will be created
  + resource "solidserver_ip_address" "ip" {
      + address = (known after apply)
      + id      = (known after apply)
      + name    = "myhost.domaine.local"
      + pool    = "TEAM1"
      + space   = "MAIN"
      + subnet  = "SIEGE"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

solidserver_ip_address.ip: Creating...
solidserver_ip_address.ip: Creation complete after 0s [id=148898]
```
Since we set a FQDN in the name argument, the DNS entry is correctly created:
```
$ host myhost.domaine.local
myhost.domaine.local has address 128.1.231.3
```
But if we go to the WebUI:
![Screenshot from 2022-08-29 16-27-52](https://user-images.githubusercontent.com/6660525/187225653-68a3cf2c-06fe-4221-bde4-d5691a8ee5d3.png)
And we try to add an alias by clicking on the "Edit" button in the "ALIASES" box:
![Screenshot from 2022-08-29 16-28-44](https://user-images.githubusercontent.com/6660525/187225882-2c492ddd-b8af-440c-a85e-ebba2c229c00.png)
We have a warning on the "IP address name" field, which is missing the name we defined with terraform, and the "IPAM to DNS replication" section is empty, so we have to re-enter the hostname.

Is it possible to provide missing information via the API so we can add it to the provider?

**Comment by pablo-ruth** [comment]
And I have the same problem when trying to create the IP via the solidserver-go-client library: https://github.com/EfficientIP-Labs/solidserver-go-client/blob/main/sdsclient/docs/IpamApi.md#ipamaddressadd

**Comment by alexissavin** [comment]
Hello,

Your issue is not with the terraform provider nor the go-client.

Your IPAM is configured to use the automatic construction of the IP name, from the class parameters 'hostname' and 'domain' (Refers to the SOLIDserver_Administrator_Guide for details - Look for 'IP Address Advanced Properties').

As a result, in addition to the name of the IP address, you need to provide the class parameters 'hostname' and 'domain' while creating IP resources.

Kind regards.

**Comment by pablo-ruth** [comment]
Oh ok, sorry for the wrong analysis. And thanks for your solution resolving our issue :)
