### ISSUE TITLE
can't use the provider inside an alpine base docker container

### ISSUE THREAD

**Issue by aniskh** [EfficientIP-Labs/terraform-provider-solidserver#12]
Hello All,
I'm trying to use the provider in an alpine base docker container but it is not working. 
I'm using terraform version 1.0.3:

bash-5.1# terraform version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/e-breuninger/netbox v1.6.7
+ provider registry.terraform.io/efficientip-labs/solidserver v1.1.14
+ provider registry.terraform.io/hashicorp/vsphere v2.2.0

To reproduce the error:
1- create a terraform module that uses the provider ( i'm using version 1.1.14)
2- run terraform init
3 - run terraform plan 
The error is the following:

│
│ failed to instantiate provider "registry.terraform.io/efficientip-labs/solidserver" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/efficientip-labs/solidserver/1.1.14/linux_amd64/terraform-provider-solidserver_v1.1.14: no such file or directory
│

Thanks for the help,
Regards.

**Comment by alexissavin** [comment]
Hello,

Not sure this is a problem with the provider itself: https://github.com/hashicorp/terraform/issues/24010

As indicated in this thread, I advise you to remove the corrupted the .terraform directory then re-initializing it to the correct course of action.

Kind regards.

**Comment by aniskh** [comment]
Thanks [alexissavin](https://github.com/alexissavin) for your reply, actually, i tried that but didn't work.
Finally, i used the latest version `1.1.17` and the code worked fine.
Best regards.

**Comment by alexissavin** [comment]
Possibly related to fixed issue https://github.com/EfficientIP-Labs/terraform-provider-solidserver/issues/5 then.

**Comment by aniskh** [comment]
Yes probably, sorry, i didn't notice that issue, closing this issue.
Regards.
