### ISSUE TITLE
Add feature to solidserver_dns_rr module - class parameters?

### ISSUE THREAD

**Issue by nobiac0922** [EfficientIP-Labs/terraform-provider-solidserver#13]
I'm trying to automate our provisioning of DNS records in EIP and so far the module works well in creating those records using **terraform-provider-solidserver v1.1.17** (Thank you!). The challenge I have now is in terms of operation of existing DNS records created using EIP's WEBUI and new resource records provisioned using terraform.

Basically, I need to distinguish which DNS record is managed from terraform and which one is not to avoid any potential conflict in configuration where someone modified a record in WEBUI that is provisioned in terraform. In **solidserver_ip_address** module, I can easily do this using class parameters. However in **solidserver_dns_rr** module, there is no available attribute for this. I'm not sure if it is a limitation in DNS part, but is it possible to add a similar feature into this?

**Comment by alexissavin** [comment]
Hello @nobiac0922,

Actually SOLIDserver 8.0 introduce class_parameters on DNS RR(s).
However, I did not yet implemented support in the provider.
I will try to have a look as soon as possible, this is not a lot of work.

However, beware that DNS RR(s) can be dynamic, and that in some cases,
they can be deleted a then recreated without their class parameters (mostly
when using DNS Update requests, for instance when MS clients connect to a domain).

Let me know if that would be an applicable option in your case so I can prioritize accordingly.

Kind regards

**Comment by nobiac0922** [comment]
Thank you @alexissavin for your prompt response. This is a definitely an applicable case for us to have class parameters option in solidserver_dns_rr. And yes we are already running version 8.0. 

In terms of dynamic DNS RR(s), we will probably won't managed them through Terraform and let the AD DNS to update those records automatically to avoid any potential conflict with Terraform state and changes outside terraform.

Just curious though, do you have an estimated timeline on when this feature will be available? and this not in any way to rush your team :) but it is more of project planning on my end. Thank you.

**Comment by alexissavin** [comment]
Hello,

Latest commit 3fec376720901def70d0f2cd0ec3f55037970b25 embeds update for SDKv2 and as well as support for RR class parameters. You can give it a try from the master branch.

Kind regards

**Comment by nobiac0922** [comment]
Hi Alexis,

I tested the latest commit and it works as expected. I initially tried to use "Select" class object in Class Studio for the class parameter that I added and I couldn't make it work, not sure if I'm doing it right though.. But using "Input" in class studio, works fine and meets our requirement. Do you know by any chance when the new terraform provider will be available in terraform registry?

Once again, thanks for your quick update on this and I really appreciate your help!

**Comment by alexissavin** [comment]
Hello,

Glad to read it provide you a suitable option.

I'm still working on the migration the SDKv2.
Will most likely publish a new version in the coming month.
Possibly a major release, some changes might not be compatible (To be further investigated/tested).

Kind regards

**Comment by nobiac0922** [comment]
Hi there, just want to check if there any update on this?

**Comment by alexissavin** [comment]
Released in version v1.1.18
