### ISSUE TITLE
Retrieve Container value

### ISSUE THREAD

**Issue by MethylHaine** [EfficientIP-Labs/terraform-provider-solidserver#17]
### Overview of the Feature Request

As of today, it is not possible to retrieve the **_Container_** value of a specified VLAN :
```tf
resource "solidserver_ip_address" "server" {
    name   = var.servername
    space  = var.ipam-space
    subnet = var.server-subnet-name
}
```
Which implies that it is not possible to assign an IP using VLAN Name combined with the **_Container_** value.

### Expected Behavior

We should be able to assign IPs to our objects by giving a VLAN Name combined with its **_Container_** value.
Maybe something like :
```tf
resource "solidserver_ip_address" "server" {
    name      = var.servername
    space     = var.ipam-space
    subnet    = var.server-subnet-name
    container = var.server-container-name
}
```

### Operating system and Environment details

Running on **Terraform:1.3.5** and **EfficientIP-Labs/solidserver:1.1.17** :
```tf
terraform {
    required_providers {
        solidserver = {
            source  = "EfficientIP-Labs/solidserver"
            version = ">= 1.1.17
        }
    }
}
```

**Comment by alexissavin** [comment]
Hello,

Sorry for the latency, but I'm struggling to understand your request.
There is no concept of container in the SOLIDserver. What are you referring to ?

Kind regards

**Comment by MethylHaine** [comment]
Hi Alexis,
Thanks for your reply, and sorry for the misunderstanding.
I meant Parent Network.

My issue is that I cannot find a way to create a resource in blocks having duplicate names across different parent blocks.
Let's say I have the following configuration :
```java
SPACE
  - Block: PROD
   `- Block: DC1 - 10.1.0.0/16
   | `- Terminal: MANAGEMENT - 10.1.0.0/24
   `- Block: DC2 - 10.2.0.0/16
     `- Terminal: MANAGEMENT - 10.2.0.0/24
```
How can I create my resource in the `MANAGEMENT` Terminal Network from the `DC2` block ?
I think I'm looking for a way to specify my whole network tree when creating the resource.

My issue may be linked to this one :
https://github.com/EfficientIP-Labs/terraform-provider-solidserver/issues/18
