### ISSUE TITLE
Add the capability to create dhcp-scope

### ISSUE THREAD

**Issue by jorgenspange** [EfficientIP-Labs/terraform-provider-solidserver#25]
When creating subnet in the gui you are able to check off for "create dhcp scope", would be nice to have this option in the terraform provider aswell so that you can provision a new subnet with a dhcp-scope.

**Comment by alexissavin** [comment]
I'm not sure this is from the base product, this might be a customization.

I suggest you consult EfficientIP professional services (TAM, support) or one of our customer solution atchitect.

Kind regards
