### ISSUE TITLE
Last available subnet within a space

### ISSUE THREAD

**Issue by jorgenspange** [EfficientIP-Labs/terraform-provider-solidserver#27]
Good day,

Thanks for all the nice work done with the solidserver provider.

I have a feature request, for being able to get last available subnet within a space when using the solidserver_ip_subnet module.

I know it probably makes more sense to abstract yourself from that kind of structure once you go IaC, but as of now it would be a nice feature for us.

Br
Jørgen

**Comment by alexissavin** [comment]
Hello Jørgen,

Could you please clarify your request, what exactly do you define as the "Last available subnet within a space" ?

If you have an example, I'm interested. I'm not sure we have the same definition in mind.

Thanks in advance.

Kind regards

**Comment by jorgenspange** [comment]
Hello,

Sorry for being unprecise.

Say you have a /23 subnet: 192.168.0.0/23.

If you split this into two /24 subnets, you'll get:

First subnet: 192.168.0.0/24
Last subnet: 192.168.1.0/24

So what I mean is that I want to be able to acquire the "last" subnet in this range. 

Usually when we build new things we aim to have the server subnets first in the range and the link-nets etc in the end of the range.

Hope that clears things up.

Best regards.

**Comment by alexissavin** [comment]
Hello,

Unfortunately, the SOLIDserver API (/rpc/rpc/ip_find_free_subnet) that returns the  best matches intends to minimize
the fragmentation of the IP space and therefore only returns available subnets from the beginning of the prefix.

Implementing this logic from within the provider would not make sense, this 'feature' needs to be implemented in the SOLIDserver API itself.

Kind regards.
