### ISSUE TITLE
Custom sTimeout value

### ISSUE THREAD

**Issue by murathatipoglu** [EfficientIP-Labs/terraform-provider-solidserver#32]
Hi,

Here is the default msSweep, sTimeout, and maxTry values are set

https://github.com/EfficientIP-Labs/terraform-provider-solidserver/blob/fb9d8c8409cc3ca6bd23fcece2271d56d40cca37/solidserver/soliderver.go#L38-L42

I understand for post, put, delete the maxTry should be left as 1 to avoid any repetition of the same modification request.

IS it possible to set a higher sTimeout value when communicating with Solid Server API through terraform provider? We are frequently getting errors from Solid Server API and deployment pipelines using Solid Server terraform provider fails. Most of the time re-run of the pipeline succeed. Sometime it requires third or fourth re-run

We mainly use DNS RR resource. Is there way to set timeout to a higher value at general provider level settings or specifically for dns rr resource level?

Thank you.

**Comment by alexissavin** [comment]
Hello @murathatipoglu,

I would better recommend you to adjust the number of concurrent operations performed by terraform using the option "-parallelism = <value>" or the TFE_PARALLELISM environment variable.

Default value is 10 which, depending on your TF script, can trigger a lot of operations. Maybe consider using a lower value such as 4 or even 2.

Kind regards

**Comment by murathatipoglu** [comment]
Hi @alexissavin 

Thanks for your kind reply and recommendation

The API endpoint on solid server side is getting number of concurrent  queries from different sources. Thus, lowering parallelism would not help to lower load on server side.

By the way, we created a custom copy of the provider and changed the sTimeout to higher values. That fixed the issue and not getting errors caused by hitting timeout.

The workload running pipeline/deployment is running in public cloud environment where solid server is in an on-prem data center. There is a latency in between and we believe "3 seconds" is -sometimes- not enough and should be set to a higher value.

Is there a way to pass custom sTimeout value to solid server provider (or DNS_rr resource)? Or are those values are statically fixed in terraform-provider-solidserver/solidserver/soliderver.go file? (https://github.com/EfficientIP-Labs/terraform-provider-solidserver/blob/fb9d8c8409cc3ca6bd23fcece2271d56d40cca37/solidserver/soliderver.go#L38-L42)

As far as I see, it is the second case. Would it be possible to add support for passing those values as parameters to the provider in TF code.

Best regards.

**Comment by murathatipoglu** [comment]
Thanks very much Alex. I checked latest two commits to introduce new Timeout parameter and replace static 10s and 3s timeout values with the new dynamic parameter. That is exactly what I asked for. You're awesome!

**Comment by alexissavin** [comment]
Addressed in v1.1.21.
