### ISSUE TITLE
Provider not available for Terraform on Windows x86

### ISSUE THREAD

**Issue by IanT111** [EfficientIP-Labs/terraform-provider-solidserver#44]
The Terraform provider does have a supported provider for Windows

>> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding efficientip-labs/solidserver versions matching "~> 1.1.0"...

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/efficientip-labs/solidserver v1.1.21 does not have a package available for your current platform, windows_386.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.

**Comment by alexissavin** [comment]
Hello @IanT111,
I just pushed the binary to the release and sync the registry.
The provider should now be available for windows386.
Please let me know if that is ok.
Kind regards

**Comment by IanT111** [comment]
Looks good now on Windows:

terraform --version
Terraform v1.6.3
on windows_386
+ provider registry.terraform.io/efficientip-labs/solidserver v1.1.22

Your version of Terraform is out of date! The latest version
is 1.9.2. You can update by downloading from https://www.terraform.io/downloads.html

Thanks for the quick turn around!
