### ISSUE TITLE
Fix case sensitivity of the solidserver provider's environment variables

### ISSUE THREAD

**Issue by AshishDadhich4h2** [EfficientIP-Labs/terraform-provider-solidserver#46]
On the Linux agents - the environment variable must be set as SOLIDServer_HOST. A variable set as SOLIDSERVER_HOST is not accepted by the provider.
We can’t utilize the native behavior of Azure ADO that stores pipeline variables as environment variables. ADO capitalizes all variable names when storing them as environment variables - and that makes them unusable for the solidserver provider.
Is it possible to allow the provider for accepting requested following input variables as case-insensitive?

SOLIDServer_HOST
SOLIDServer_USERNAME
SOLIDServer_PASSWORD

**Comment by alexissavin** [comment]
Hello,

It's not possible to be case-insensitive here, but using 'MultiEnvDefaultFunc' instead of 'EnvDefaultFunc' is an option.
In such scenario, both SOLIDServer_HOST and SOLIDSSERVER_HOST would be supported but not any other case combination.
I will give it a try as soon as possible.

Kind regards

**Comment by AshishDadhich4h2** [comment]
Thank you @alexissavin !

**Comment by alexissavin** [comment]
Hello @AshishDadhich4h2,
Latest commit address the issue, you can build the master branch or wait for the next release.
Kind regards

**Comment by AshishDadhich4h2** [comment]
@alexissavin Thank you for quick updates! 
Do you know tentatively when next release will be published?

**Comment by makeacode** [comment]
Any ETA on this feature being released?  Also in need of this fix

**Comment by AshishDadhich4h2** [comment]
@alexissavin would you please check and update when next release will be published.

**Comment by alexissavin** [comment]
Fixed in v1.1.23
