### ISSUE TITLE
Terraform provider reporting "unable to find suitable suffix" when multiple blocks exist with the same name and one is full

### ISSUE THREAD

**Issue by IanTurtle** [EfficientIP-Labs/terraform-provider-solidserver#49]
Provision two non-terminal blocks with the same name:

e.g.
UK South: with CIDR 10.1.0.0/16 in space test
UK South: with CIDR 10.9.0.0/16 in space test

```
resource "solidserver_ip_subnet" "test" {
  space = "test"
  block = "UK South"
  prefix_size = 17
  name = "mySecondIPSubnet"
  terminal = true
}
```
```
resource "solidserver_ip_subnet" "test2" {
  space = "test"
  block = "UK South"
  prefix_size = 17
  name = "myFirstIPSubnet"
  terminal = true
}
```
```
resource "solidserver_ip_subnet" "test3" {
  space = "test"
  block = "UK South"
  prefix_size = 17
  name = "myThirdIPSubnet"
  terminal = true
}
```

I would expect two to be deployed into one block, and the third to be deployed into the second, instead I receive "unable to find suitable suffix"

I appreciate there is already an issue reporting this: https://github.com/EfficientIP-Labs/terraform-provider-solidserver/issues/18 however it was closed, and I have a use case where this feature would be helpful (added as a comment to the previous issue, but including here to keep it all in one place):

We have a situation where we deploy resources across multiple regions within a cloud, but have run out of space in one of the regions and need to allocate an additional CIDR. However the next contiguous block of IPs has already been allocated, so we end up in the following situation:

Original UK South - 10.1.0.0/16
Original UK West - 10.2.0.0/16
New UK South - 10.3.0.0/16

What I would like to be able to do is create two blocks called "UK South", and then leave it up to Terraform/EfficientIP to decide which block to create the subnet in, since we really don't care which one it creates it in. Rather than us having to call the REST API to determine which one is emptier.

**Comment by alexissavin** [comment]
Hello,

Sorry, but this is somehow an intended limitation, see duplicate issue #18.

Kind regards

**Comment by IanTurtle** [comment]
I saw that issue, and that you were asking for a use case - however they didnt provide one. Is the one I have provided not sufficient to get the feature added? @alexissavin

**Comment by alexissavin** [comment]
I do not consider it a valid case, sorry. Having the same name for different network is a blocking point.
The IPAM allows it and changing this behavior would be a problem for many EIP customer I guess.

However, using terraform it would be unpractical. If not using the name as unique identifier for the network,
the only foreseeable option would require to use the entire prefix which make no sense to me in the context
of automatic provisioning. Using some kind of a path would have been an option, but you can still create
duplicate names at the same level in the IPAM tree.
